version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=vehiclix;Username=postgres;Password=your_password
      - Jwt__Key=your-super-secret-key-with-minimum-16-characters
      - Jwt__Issuer=vehiclix-api
      - Jwt__Audience=vehiclix-client
      - Jwt__DurationInMinutes=60
      - Sentry__Dsn=your-sentry-dsn
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vehiclix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 